# Generated by Django 3.2.2 on 2021-05-11 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mod5_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipebook',
            name='title',
        ),
        migrations.AddField(
            model_name='recipebook',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipebook',
            name='carbs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipebook',
            name='image',
            field=models.TextField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipebook',
            name='label',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipebook',
            name='protein',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipebook',
            name='servings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipebook',
            name='url',
            field=models.TextField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Mod5_backend_app.recipebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
