# Generated by Django 3.2.2 on 2021-05-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mod5_backend_app', '0002_auto_20210511_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipebook',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipebook',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='recipebook',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipebook',
            name='label',
        ),
        migrations.RemoveField(
            model_name='recipebook',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='recipebook',
            name='servings',
        ),
        migrations.RemoveField(
            model_name='recipebook',
            name='url',
        ),
        migrations.AddField(
            model_name='recipebook',
            name='recipe',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
