# Generated by Django 3.2.3 on 2021-05-26 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mod5_backend_app', '0003_auto_20210512_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='users',
            field=models.ManyToManyField(related_name='users', through='Mod5_backend_app.FavoriteRecipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='recipebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to='Mod5_backend_app.recipebook'),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
