# Generated by Django 3.2.2 on 2021-05-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mod5_backend_app', '0003_auto_20210512_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=32, null=True)),
                ('url', models.CharField(max_length=32, null=True)),
                ('calories', models.IntegerField(default=0, null=True)),
                ('carbs', models.IntegerField(null=True)),
                ('protein', models.IntegerField(null=True)),
                ('servings', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='favoriterecipe',
            name='recipebook',
        ),
        migrations.DeleteModel(
            name='RecipeBook',
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='recipe',
            field=models.ForeignKey(default='RecipeName', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Mod5_backend_app.recipe'),
            preserve_default=False,
        ),
    ]
